(() => {
"use strict";
const K="psdeals_bitacora"; const POR_PAGINA=20; let pagina=1; let filtrados=[];
const $=s=>document.querySelector(s); const leer=()=>PSAuth.leer(K,[]).sort((a,b)=>new Date(b.fecha)-new Date(a.fecha));
const normal=s=>String(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");
function tipo(e){const a=normal(e.accion);if(a.includes("sesion")||a.includes("acceso"))return"acceso";if(a.includes("venta")||a.includes("codigo"))return"ventas";if(a.includes("inventario")||a.includes("producto")||a.includes("compra"))return"inventario";if(a.includes("cliente"))return"clientes";if(a.includes("gasto")||a.includes("cobran")||a.includes("apartado")||a.includes("devolucion"))return"finanzas";if(a.includes("usuario"))return"usuarios";return"sistema"}
function icono(t){return{acceso:"bi-door-open",ventas:"bi-cart-check",inventario:"bi-box-seam",clientes:"bi-people",finanzas:"bi-wallet2",usuarios:"bi-person-gear",sistema:"bi-gear"}[t]}
function fechaLocal(iso){return new Intl.DateTimeFormat("es-MX",{dateStyle:"medium",timeStyle:"short"}).format(new Date(iso))}
function aplicar(){const q=normal($("#busqueda").value),u=$("#filtroUsuario").value,t=$("#filtroTipo").value,d=$("#fechaDesde").value,h=$("#fechaHasta").value;filtrados=leer().filter(e=>{const texto=normal(`${e.usuario} ${e.accion} ${e.detalle}`);const f=String(e.fecha||"").slice(0,10);return(!q||texto.includes(q))&&(!u||e.usuario===u)&&(!t||tipo(e)===t)&&(!d||f>=d)&&(!h||f<=h)});pagina=1;render()}
function render(){const inicio=(pagina-1)*POR_PAGINA,lista=filtrados.slice(inicio,inicio+POR_PAGINA);$("#contador").textContent=`${filtrados.length} resultados`;$("#totalEventos").textContent=filtrados.length;$("#timeline").innerHTML=lista.length?lista.map(e=>`<article class="event"><span class="event-icon"><i class="bi ${icono(tipo(e))}"></i></span><div><h4>${PSAuth.escapeHTML(e.accion)}</h4><p>${PSAuth.escapeHTML(e.detalle||"Sin detalle")}</p></div><div class="event-meta"><strong>${PSAuth.escapeHTML(e.usuario||"Sistema")}</strong><small>${fechaLocal(e.fecha)}</small></div></article>`).join(""):`<div class="empty"><i class="bi bi-inbox fs-1"></i><h3>Sin actividad para mostrar</h3><p>Ajusta los filtros o realiza una operación en el sistema.</p></div>`;paginar()}
function paginar(){const total=Math.ceil(filtrados.length/POR_PAGINA),c=$("#paginacion");c.innerHTML="";for(let i=1;i<=total;i++){if(total>8&&Math.abs(i-pagina)>2&&i!==1&&i!==total)continue;const b=document.createElement("button");b.textContent=i;b.className=i===pagina?"active":"";b.onclick=()=>{pagina=i;render();scrollTo({top:0,behavior:"smooth"})};c.appendChild(b)}}
function resumen(){const todos=leer(),hoy=new Date().toISOString().slice(0,10);$("#eventosHoy").textContent=todos.filter(e=>String(e.fecha).slice(0,10)===hoy).length;$("#usuariosActivos").textContent=new Set(todos.map(e=>e.usuario).filter(Boolean)).size;$("#eventosAcceso").textContent=todos.filter(e=>tipo(e)==="acceso").length;$("#eventosOperacion").textContent=todos.filter(e=>tipo(e)!=="acceso").length}
function usuarios(){const s=$("#filtroUsuario");[...new Set(leer().map(e=>e.usuario).filter(Boolean))].sort().forEach(u=>s.insertAdjacentHTML("beforeend",`<option>${PSAuth.escapeHTML(u)}</option>`))}
function exportar(){const filas=[["Fecha","Usuario","Tipo","Acción","Detalle"],...filtrados.map(e=>[e.fecha,e.usuario,tipo(e),e.accion,e.detalle])];const csv=filas.map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n");const blob=new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`PS-DEALS-actividad-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href);PSAuth.registrar("Actividad exportada",`${filtrados.length} eventos en CSV`)}
function sidebar(){const s=$("#sidebar"),b=$("#sidebarBackdrop");$("#btnAbrirSidebar").onclick=()=>{s.classList.add("open");b.classList.add("show")};const cerrar=()=>{s.classList.remove("open");b.classList.remove("show")};$("#btnCerrarSidebar").onclick=cerrar;b.onclick=cerrar}
document.addEventListener("DOMContentLoaded",()=>{usuarios();resumen();filtrados=leer();render();["#busqueda","#filtroUsuario","#filtroTipo","#fechaDesde","#fechaHasta"].forEach(id=>$(id).addEventListener(id==="#busqueda"?"input":"change",aplicar));$("#btnLimpiar").onclick=()=>{$("#busqueda").value="";$("#filtroUsuario").value="";$("#filtroTipo").value="";$("#fechaDesde").value="";$("#fechaHasta").value="";aplicar()};$("#btnExportar").onclick=exportar;$("#btnImprimir").onclick=()=>window.print();sidebar()})
})();