const K_COMPRAS="psdeals_compras",K_PROV="psdeals_proveedores";
const $=id=>document.getElementById(id);
const modalProveedor=new bootstrap.Modal($("modalProveedor")),modalCompra=new bootstrap.Modal($("modalCompra"));
let compras=[],proveedores=[],items=[],productosCatalogo=[];
const moneda=v=>Number(v||0).toLocaleString("es-MX",{style:"currency",currency:"MXN"});
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const hoy=()=>new Date().toISOString().slice(0,10);
async function api(url,options={}){const response=await fetch(url,{headers:{"Content-Type":"application/json",...(options.headers||{})},...options});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`Error HTTP ${response.status}`);return data;}
function cache(){localStorage.setItem(K_COMPRAS,JSON.stringify(compras));localStorage.setItem(K_PROV,JSON.stringify(proveedores));}
function mostrarError(id,error){const box=$(id);box.className="alert alert-danger mt-3 mb-0";box.textContent=error.message||String(error);}
function poblar(){
 $("compraProveedor").innerHTML='<option value="">Selecciona proveedor</option>'+proveedores.map(p=>`<option value="${p.id}">${esc(p.nombre)}</option>`).join("");
 $("productoCompra").innerHTML='<option value="">Selecciona producto</option>'+productosCatalogo.filter(p=>p.disponible!==false).map(p=>`<option value="${p.id}">${esc(p.nombre)} · stock ${Number(p.stock||0)}</option>`).join("");
}
function renderProveedores(){
 $("statProveedores").textContent=proveedores.length;
 $("listaProveedores").innerHTML=proveedores.length?proveedores.map(p=>`<div class="supplier-item"><strong>${esc(p.nombre)}</strong><small>${esc(p.contacto||"Sin contacto")} · ${esc(p.telefono||"Sin teléfono")}</small><div class="supplier-actions"><button class="btn btn-sm btn-outline-secondary" onclick="editarProveedor(${p.id})"><i class="bi bi-pencil"></i></button> <button class="btn btn-sm btn-outline-danger" onclick="eliminarProveedor(${p.id})"><i class="bi bi-trash"></i></button></div></div>`).join(""):'<div class="empty-state"><i class="bi bi-buildings fs-2 d-block mb-2"></i>Agrega tu primer proveedor.</div>';
}
function resumen(){const now=new Date(),mes=compras.filter(c=>c.estado!=="cancelada"&&(()=>{const f=new Date(c.fecha);return f.getMonth()===now.getMonth()&&f.getFullYear()===now.getFullYear()})());const total=mes.reduce((s,c)=>s+Number(c.total||0),0),unidades=compras.filter(c=>c.estado!=="cancelada").reduce((s,c)=>s+c.items.reduce((a,i)=>a+Number(i.cantidad),0),0),pend=compras.filter(c=>c.estado!=="cancelada"&&c.estadoPago==="Pendiente").reduce((s,c)=>s+Number(c.total||0),0);$("heroComprasMes").textContent=$("statComprasMes").textContent=moneda(total);$("statOperacionesMes").textContent=`${mes.length} operaciones`;$("statUnidades").textContent=unidades;$("statPendiente").textContent=moneda(pend);}
function renderCompras(){const q=$("buscarCompras").value.toLowerCase(),estado=$("filtroPago").value;const arr=compras.filter(c=>(estado==="todas"||c.estadoPago===estado)&&(!q||[c.folio,c.proveedor,c.documento,...c.items.map(i=>i.nombre)].join(" ").toLowerCase().includes(q)));$("tablaCompras").innerHTML=arr.length?arr.map(c=>`<tr class="${c.estado==="cancelada"?"table-light text-muted":""}"><td>${new Date(c.fecha).toLocaleDateString("es-MX")}</td><td>${esc(c.folio)}${c.estado==="cancelada"?' <span class="badge bg-secondary">Cancelada</span>':""}</td><td>${esc(c.proveedor)}</td><td>${esc(c.items.length===1?c.items[0].nombre:`${c.items[0]?.nombre||""} +${Math.max(0,c.items.length-1)}`)}<div class="small text-muted">${c.items.reduce((s,i)=>s+Number(i.cantidad),0)} unidades</div></td><td><span class="badge-status ${c.estadoPago==="Pagada"?"status-paid":"status-pending"}">${esc(c.estadoPago)}</span></td><td class="text-end"><strong>${moneda(c.total)}</strong></td><td class="text-end">${c.estado!=="cancelada"?`<button class="btn btn-sm btn-outline-danger" onclick="cancelarCompra(${c.id})" title="Cancelar y revertir inventario"><i class="bi bi-x-circle"></i></button>`:""}</td></tr>`).join(""):'<tr><td colspan="7" class="empty-state">No hay compras registradas.</td></tr>';}
function renderItems(){$("tablaItemsCompra").innerHTML=items.length?items.map((i,n)=>`<tr><td>${esc(i.nombre)}</td><td>${i.cantidad}</td><td>${moneda(i.costo)}</td><td>${moneda(i.cantidad*i.costo)}</td><td><button type="button" class="btn btn-sm btn-outline-danger" onclick="quitarItem(${n})"><i class="bi bi-x"></i></button></td></tr>`).join(""):'<tr><td colspan="5" class="empty-state">Agrega productos a la compra.</td></tr>';$("totalCompra").textContent=moneda(items.reduce((s,i)=>s+i.cantidad*i.costo,0));}
function todo(){poblar();renderProveedores();resumen();renderCompras();}
async function cargar(){try{const [p,c,pr]=await Promise.all([api("/api/suppliers"),api("/api/purchases"),api("/api/catalog/products")]);proveedores=p.proveedores;compras=c.compras;productosCatalogo=pr.productos;cache();todo();}catch(error){console.error(error);alert(`No se pudieron cargar las compras desde SQLite: ${error.message}`);}}
$("btnNuevoProveedor").onclick=()=>{$("formProveedor").reset();$("proveedorId").value="";$("tituloProveedor").textContent="Nuevo proveedor";$("mensajeProveedor").className="alert d-none mt-3 mb-0";modalProveedor.show();};
$("formProveedor").onsubmit=async e=>{e.preventDefault();const pid=Number($("proveedorId").value||0),body={nombre:$("proveedorNombre").value.trim(),telefono:$("proveedorTelefono").value.trim(),correo:$("proveedorCorreo").value.trim(),contacto:$("proveedorContacto").value.trim(),notas:$("proveedorNotas").value.trim()};const btn=e.submitter;btn.disabled=true;try{await api(pid?`/api/suppliers/${pid}`:"/api/suppliers",{method:pid?"PUT":"POST",body:JSON.stringify(body)});modalProveedor.hide();await cargar();}catch(error){mostrarError("mensajeProveedor",error);}finally{btn.disabled=false;}};
window.editarProveedor=pid=>{const p=proveedores.find(x=>Number(x.id)===Number(pid));if(!p)return;$("proveedorId").value=p.id;$("proveedorNombre").value=p.nombre;$("proveedorTelefono").value=p.telefono||"";$("proveedorCorreo").value=p.correo||"";$("proveedorContacto").value=p.contacto||"";$("proveedorNotas").value=p.notas||"";$("tituloProveedor").textContent="Editar proveedor";modalProveedor.show();};
window.eliminarProveedor=async pid=>{if(!confirm("¿Desactivar este proveedor? Su historial de compras se conservará."))return;try{await api(`/api/suppliers/${pid}`,{method:"DELETE"});await cargar();}catch(error){alert(error.message);}};
$("btnNuevaCompra").onclick=()=>{if(!proveedores.length){alert("Primero registra un proveedor.");return;}items=[];$("formCompra").reset();$("compraFecha").value=hoy();$("mensajeCompra").className="alert d-none mt-3 mb-0";renderItems();poblar();modalCompra.show();};
$("productoCompra").onchange=()=>{const p=productosCatalogo.find(x=>Number(x.id)===Number($("productoCompra").value));$("costoCompra").value=p?Number(p.costo||0):"";};
$("btnAgregarItem").onclick=()=>{const p=productosCatalogo.find(x=>Number(x.id)===Number($("productoCompra").value)),cantidad=Number($("cantidadCompra").value),costo=Number($("costoCompra").value);if(!p||cantidad<=0||costo<0){alert("Selecciona producto, cantidad y costo válidos.");return;}const ex=items.find(i=>i.productoId===Number(p.id));if(ex){ex.cantidad+=cantidad;ex.costo=costo;}else items.push({productoId:Number(p.id),nombre:p.nombre,cantidad,costo});renderItems();};
window.quitarItem=n=>{items.splice(n,1);renderItems();};
$("formCompra").onsubmit=async e=>{e.preventDefault();if(!items.length){alert("Agrega al menos un producto.");return;}const btn=e.submitter;btn.disabled=true;try{const result=await api("/api/purchases",{method:"POST",body:JSON.stringify({proveedorId:Number($("compraProveedor").value),fecha:$("compraFecha").value,estadoPago:$("compraEstadoPago").value,documento:$("compraDocumento").value.trim(),notas:$("compraNotas").value.trim(),items})});modalCompra.hide();await cargar();alert(`Compra ${result.compra.folio} registrada. Inventario y costo promedio actualizados.`);}catch(error){mostrarError("mensajeCompra",error);}finally{btn.disabled=false;}};
window.cancelarCompra=async id=>{const motivo=prompt("Motivo de cancelación:","Captura incorrecta");if(motivo===null)return;if(!confirm("Se descontarán del inventario las unidades recibidas. ¿Continuar?"))return;try{await api(`/api/purchases/${id}/cancel`,{method:"POST",body:JSON.stringify({motivo})});await cargar();alert("Compra cancelada e inventario revertido.");}catch(error){alert(error.message);}};
$("buscarCompras").oninput=renderCompras;$("filtroPago").onchange=renderCompras;
$("btnAbrirSidebar").onclick=()=>{$("sidebar").classList.add("open");$("sidebarBackdrop").classList.add("show")};function cerrar(){$("sidebar").classList.remove("open");$("sidebarBackdrop").classList.remove("show")}$("btnCerrarSidebar").onclick=cerrar;$("sidebarBackdrop").onclick=cerrar;
cargar();
